### ISSUE TITLE
Test NeXus workflow

### ISSUE THREAD

**Issue by jl-wynen** [scipp/essreduce#103]
`LoadNeXusWorkflow` is currently untested. We should change that!

**Comment by SimonHeybrock** [comment]
Most of the components are tested in https://github.com/scipp/essreduce/blob/main/tests/nexus/generic_workflow_test.py and https://github.com/scipp/essreduce/blob/main/tests/nexus/workflow_test.py. `LoadNeXusWorkflow` itself is a helper that is currently not (and may never) be used by anything. It is meant as a quick helper to work with unknown files, so it is unclear what its future will be.
