### ISSUE TITLE
UX improvements for our workflows

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/essreduce#21]
### Context

In a recent call with an instrument scientist it became clear that our notebooks of reduction workflows are unnecessarily unclear for non-programmers, even when considering an expert user who *does* want to see and access all the details.

Based on my notes, here are a couple of suggestions of potential improvements.

### Suggestions

1. Replace "providers" with "workflow steps", avoiding Sciline terminology.
2. Replace "pipeline" with "reduction".
3. Avoid param dicts: Mixing of collecting/setting params in a dict as well as setting them on a `Pipeline` is confusing. It is not obvious to users that this is equivalent.
4. Add wrappers for pipeline creation that include defaults, mainly to facilitate 3.) above.

### Example

Change
```python
params = loki.default_parameters()
params[QBins] = ...
pipeline = sciline.Pipeline(loki.providers, params=params)
pipeline[ReturnEvents] = True
```
to
```python
reduction = loki.LokiReduction()
reduction[QBins] = ...
reduction[ReturnEvents] = True
```
If customization of providers is required, we can have something like
```python
reduction = sans.Reduction(
    steps=loki.workflow_steps + sans.workflow_steps,
    params=loki.default_parameters())
```

**Comment by jokasimr** [comment]
Sounds like some very good suggestions.
Maybe we should even settle on either using the term "workflow" or the term "reduction"?
For example:
```python
reduction = sans.Reduction(
    steps=loki.reduction_steps + sans.reduction_steps,
    params=loki.default_parameters())
```

**Comment by SimonHeybrock** [comment]
I think we still need to distinguish two things: The "Reduction" (previously pipeline), and the "Workflow", created by it?

**Comment by jl-wynen** [comment]
From a programming point of view, I don't like the word reduction in this context. It clashes with reducing collections.
What was this scientist's opinion of 'task graph'?

Another alternative for pipeline would be 'workflow builder'.

**Comment by SimonHeybrock** [comment]
But... we are not writing this for programmers, right? I don't think you are suggesting we should not call it "data reduction" any more? And ultimately, the data reduction *is* reducing collections (a collection of data points at pixels into data for Q values).

**Comment by jl-wynen** [comment]
No, we should not try to change the name used in science. But this does not mean that we should use it as a variable name.
If you want to get philosophical, I would say that pipelines are not reductions. They represent an infinite set of possible reductions. So they are builders, not the concrete reduction/workflow.

**Comment by jokasimr** [comment]
> I think we still need to distinguish two things: The "Reduction" (previously pipeline), and the "Workflow", created by it? Not sure how the steps should be named?

Not sure what you mean. Do you mean that we should distinguish between the constructor of the pipeline and the pipeline itself, or do you mean we should distinguish between the pipeline and the task-graph created when we request a provider?

Regarding pipeline / task graph I think we should avoid creating task-graphs in the workflows and instead almost always 
do `pipeline.compute(Type)` instead of something like `ioq = pipeline.get(Type); ioq.compute()`. The latter is confusing for some users because it's easy to mix up the task graph with the result.

**Comment by SimonHeybrock** [comment]
> > I think we still need to distinguish two things: The "Reduction" (previously pipeline), and the "Workflow", created by it? Not sure how the steps should be named?
> 
> Not sure what you mean. Do you mean that we should distinguish between the constructor of the pipeline and the pipeline itself, or do you mean we should distinguish between the pipeline and the task-graph created when we request a provider?

I meant the latter.

> 
> Regarding pipeline / task graph I think we should avoid creating task-graphs in the workflows and instead almost always do `pipeline.compute(Type)` instead of something like `ioq = pipeline.get(Type); ioq.compute()`. The latter is confusing for some users because it's easy to mix up the task graph with the result.

Good point. Maybe we can avoid working with `TaskGraph`? The main reason for it is that it avoid specifying keys multiple times:

```python
iofq = pipeline.get(IofQ)
iofq.visualize()
iofq.compute()
```
vs
```python
workflow.visualize(IofQ)
workflow.compute(IofQ)
```
but maybe that is fine and less confusing?

**Comment by jl-wynen** [comment]
> Shall we discuss this online?

No we should not.

**Comment by jokasimr** [comment]
> Good point. Maybe we can avoid working with TaskGraph? The main reason for it is that it avoid specifying keys multiple times:

I prefer the second version because it's explicit about what domain type is referenced. (Is it normalized iofq, sample iofq, background iofq etc). It also has less state, which is good in a notebook where it's easy to loose track of what variables references what where.

To make it slightly less verbose we can give the Pipeline a shorter name, something like `wf` instead of `workflow`.

**Comment by nvaytet** [comment]
I think the suggestions are good, and there are also good discussion points. Let's set up a meeting to talk about this.

**Comment by nvaytet** [comment]
Summary from meeting:

- Naming: use `workflow = loki.LokiWorkflow()`
- set parameters on pipeline, do not use `params[QBins]`
- use `workflow.compute(IofQ)` instead of explicitly using the task graph in the notebooks.
